services:
  - type: web
    name: facebook-bot-debug
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: APPSTATE
        sync: false
      - key: NODE_ENV
        value: production
